FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run

ENV PULSE_SINK=virtual-sink
ENV PULSE_SERVER=unix:/pulseaudio/pulseaudio.socket

WORKDIR /usr/src
COPY . .

RUN install_packages python pkg-config make g++ libpulse-dev pulseaudio alsa-utils
RUN npm install

CMD [ "/bin/bash", "start.sh" ]