version: '2'

volumes:
  pulse:
    
services:
  google-assistant:
    build: ./google-assistant
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    volumes:
      - 'pulse:/pulseaudio'

  pulseaudio:
    build: ./pulseaudio
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.kernel-modules: 1
    volumes:
      - 'pulse:/pulseaudio'

  meet:
    build: ./meet
    ports:
      - 80:80
    volumes:
      - 'pulse:/pulseaudio'

  # pulsetest:
  #   build: ./pulsetest
  #   volumes:
  #     - 'pulse:/pulseaudio'
