version: '2'
volumes:
  google_assistant_credentials_data:
services:
  google_assistant:
    build: ./google_assistant
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - 'google_assistant_credentials_data:/root/.config/google-oauthlib-tool'
    labels:
      io.balena.features.kernel-modules: '1'
  pi-join-meet:
    build: ./pi-join-meet
    restart: always
    network_mode: host
    privileged: true