version: '2'

volumes:
  pulse:
    
services:
  pulseaudio:
    build: ./pulseaudio
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.kernel-modules: 1
    volumes:
      - 'pulse:/pulseaudio'

  google-assistant:
    build: ./google-assistant
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    volumes:
      - 'pulse:/pulseaudio'

  meet-api:
    build: ./meet-api
    restart: on-failure
    ports:
      - 4000:80
  
  meet-stream:
    build: ./meet-stream
    ports:
      - 3000:80
    volumes:
      - 'pulse:/pulseaudio'

  nginx:
    build: ./nginx
    ports:
      - 80:80