FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch

RUN apt-get update && apt-get install -yq --no-install-recommends \
  pulseaudio \
  portaudio19-dev \
  libffi-dev \
  libssl-dev \
  libmpg123-dev \
  dbus \
  espeak \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY . .

# Start app
CMD ["bash", "./start.sh"]
